from dotenv import load_dotenv
import os
load_dotenv()
class Settings:
    csv_path_url: str = os.getenv("CSV_PATH_URL")
    csv_path_url2: str = os.getenv("CSV_PATH_URL2")
    csv_path_url3: str = os.getenv("CSV_PATH_URL3")
    csv_path_url3_pareto: str = os.getenv("CSV_PATH_URL3_PARETO", os.getenv("CSV_PATH_URL3"))
    csv_path_url4: str = os.getenv("CSV_PATH_URL4")
    model_init_path_url: str = os.getenv("MODEL_INIT_PATH_URL")
    model_init_path_url2: str = os.getenv("MODEL_INIT_PATH_URL2")
    model_init_path_url3: str = os.getenv("MODEL_INIT_PATH_URL3")
    model_init_path_url3_pareto: str = os.getenv("MODEL_INIT_PATH_URL3_PARETO", os.getenv("MODEL_INIT_PATH_URL3"))
    model_init_path_url4: str = os.getenv("MODEL_INIT_PATH_URL4")
    model_init_predictor_path_url: str = os.getenv("MODEL_INIT_PREDICTOR_PATH_URL") 
    model_init_predictor_path_url2: str = os.getenv("MODEL_INIT_PREDICTOR_PATH_URL2") 
    model_init_predictor_path_url3: str = os.getenv("MODEL_INIT_PREDICTOR_PATH_URL3") 
    model_init_predictor_path_url3_pareto: str = os.getenv("MODEL_INIT_PREDICTOR_PATH_URL3_PARETO", os.getenv("MODEL_INIT_PREDICTOR_PATH_URL3"))
    model_init_predictor_path_url4: str = os.getenv("MODEL_INIT_PREDICTOR_PATH_URL4")
    model_add_path_url: str = os.getenv("MODEL_ADD_PATH_URL")
    model_add_path_url2: str = os.getenv("MODEL_ADD_PATH_URL2")
    model_add_path_url3: str = os.getenv("MODEL_ADD_PATH_URL3")
    model_add_path_url3_pareto: str = os.getenv("MODEL_ADD_PATH_URL3_PARETO", os.getenv("MODEL_ADD_PATH_URL3"))
    model_add_path_url4: str = os.getenv("MODEL_ADD_PATH_URL4")
    model_add_predictor_path_url: str = os.getenv("MODEL_ADD_PREDICTOR_PATH_URL") 
    model_add_predictor_path_url2: str = os.getenv("MODEL_ADD_PREDICTOR_PATH_URL2")
    model_add_predictor_path_url3: str = os.getenv("MODEL_ADD_PREDICTOR_PATH_URL3")
    model_add_predictor_path_url3_pareto: str = os.getenv("MODEL_ADD_PREDICTOR_PATH_URL3_PARETO", os.getenv("MODEL_ADD_PREDICTOR_PATH_URL3"))
    model_add_predictor_path_url4: str = os.getenv("MODEL_ADD_PREDICTOR_PATH_URL4")
    api_key: str = os.getenv("API_KEY")
    base_url: str = os.getenv("BASE_URL")
    api_key2: str = os.getenv("API_KEY2")
    api_key3: str = os.getenv("API_KEY3")
    api_key4: str = os.getenv("API_KEY4")
    api_key5: str = os.getenv("API_KEY5")
    api_key6: str = os.getenv("API_KEY6")
    api_key7: str = os.getenv("API_KEY7")
    api_key8: str = os.getenv("API_KEY8")
    api_key9: str = os.getenv("API_KEY9")
    base_url2: str = os.getenv("BASE_URL2")
    kg_triples_emb_path: str = os.getenv("KG_TRIPLES_EMB_PATH")
    kg_triples_emb_path2: str = os.getenv("KG_TRIPLES_EMB_PATH2")
    kg_triples_emb_path3: str = os.getenv("KG_TRIPLES_EMB_PATH3")
    kg_triples_emb_path3_pareto: str = os.getenv("KG_TRIPLES_EMB_PATH3_PARETO", os.getenv("KG_TRIPLES_EMB_PATH3"))
    kg_triples_emb_path4: str = os.getenv("KG_TRIPLES_EMB_PATH4")
    model: str = os.getenv("MODEL")

settings = Settings()
